// Este script detecta quando um dispositivo IrrigaPlay envia dados com configDevice="true"
// e automaticamente cadastra os sensores na plataforma TagoIO
//
// O fluxo é o seguinte:
// 1. Detecta a flag configDevice="true" na mensagem MQTT
// 2. Extrai o serial number (SN) da central e os dados dos sensores
// 3. Busca a central existente na TagoIO pelo serial number
// 4. Copia as tags group_id e organization_id da central
// 5. Para cada sensor em data.sens, cria um dispositivo na TagoIO
// 6. O serial number de cada sensor segue o padrão: {SN_central}_{numero_sensor}

import { Account } from "@tago-io/sdk";
import axios from "axios";

// Token da conta TagoIO com permissões para criar dispositivos
// Este token deve ser configurado como variável de ambiente
const ACCOUNT_TOKEN = "ff300c89-19a5-4446-9571-f276837dee18";
const DEFAULT_RETENTION_DAYS = 30;

const PLAN_RETENTION_DAYS: Record<string, number> = {
    essencial: 7,
    visualizacao: 7,
    avancado: 30,
    intermediario: 30,
    premium: 90,
    diamante: 90
};

const AUTO_TYPES: Record<number, string> = {
    0: "Nenhuma",
    1: "Irrigação",
    2: "Climatização",
    3: "Aquecimento",
    4: "Nebulização",
    5: "Monitoramento",
    6: "Sombreamento Simples",
    7: "Sombreamento Avançado",
    8: "Cíclico",
    9: "Iluminação"
};

const SENSOR_TYPES_BY_MOD: Record<number, string> = {
    0: "irrigation",
    1: "nutrition",
    2: "nutrition_2",
    4: "illumination",
    5: "sht",
    6: "climate"
};

const SENSOR_LABELS: Record<string, string> = {
    irrigation: "Irrigação",
    nutrition: "Nutrição",
    nutrition_2: "Nutrição 2",
    illumination: "Iluminação",
    sht: "SHT",
    climate: "ClimaPrime"
};

const SENSOR_LABELS_BY_MOD: Record<number, string> = {
    5: "SHT",
    6: "ClimaPrime"
};

function normalizeTagKey(value: any): string {
    return String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().toLowerCase();
}

function normalizeTagValue(value: any): string {
    return normalizeTagKey(value).replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
}

function getTagValue(tags: any[] | undefined, key: string): string | undefined {
    const wanted = normalizeTagKey(key);
    const tag = (tags || []).find((item) => normalizeTagKey(item?.key) === wanted);
    if (tag?.value === undefined || tag?.value === null || tag?.value === "") return undefined;
    return String(tag.value);
}

function parseRetentionDays(value: any): number | null {
    if (value === undefined || value === null || value === "") return null;
    const parsed = Number(String(value).replace(",", "."));
    if (!Number.isFinite(parsed) || parsed <= 0) return null;
    return Math.floor(parsed);
}
function getDeviceRetentionConfig(retentionDays: number): { chunk_period: "week"; chunk_retention: number } {
    const days = Math.max(1, Math.floor(Number(retentionDays) || 1));

    return {
        chunk_period: "week",
        chunk_retention: Math.min(26, Math.max(1, Math.ceil(days / 7)))
    };
}

function formatRetentionConfig(retentionDays: number): string {
    const config = getDeviceRetentionConfig(retentionDays);
    return retentionDays + " dias (" + config.chunk_retention + " " + (config.chunk_retention === 1 ? "semana" : "semanas") + ")";
}
function shouldUpdateAutoGeneratedSensorName(existingName: any, sensorNumber: string, centralSN: string, targetName: string): boolean {
    const name = String(existingName || "").trim();
    if (!name || name === targetName) return false;

    const suffix = " " + sensorNumber + " - Central " + centralSN;
    const acceptedAutoNames = [
        "Sensor" + suffix,
        "SHT" + suffix,
        "Clima" + suffix,
        "Climaprime" + suffix
    ].map((item) => item.toLowerCase());

    return acceptedAutoNames.includes(name.toLowerCase());
}
function getRetentionDaysFromTags(tags: any[] | undefined): number | null {
    const explicitRetention = parseRetentionDays(
        getTagValue(tags, "plan_retention_days") ||
        getTagValue(tags, "custom_retention_days") ||
        getTagValue(tags, "retention_days") ||
        getTagValue(tags, "retencao_dias")
    );

    if (explicitRetention) return explicitRetention;

    const planId = normalizeTagValue(
        getTagValue(tags, "plan") ||
        getTagValue(tags, "plano") ||
        getTagValue(tags, "plan_id") ||
        getTagValue(tags, "plano_id") ||
        getTagValue(tags, "plan_name")
    );

    return PLAN_RETENTION_DAYS[planId] || null;
}

function upsertTags(tags: any[] | undefined, updates: any[]): any[] {
    const updateKeys = new Set(updates.map((tag) => normalizeTagKey(tag.key)));
    return [
        ...(tags || []).filter((tag) => !updateKeys.has(normalizeTagKey(tag?.key))),
        ...updates
    ];
}

async function configureDashboardUrl(
    account: Account,
    deviceId: string,
    serialNumber: string,
    sensorType: string,
    groupId?: string,
    organizationId?: string
): Promise<void> {
    const dashboardMap: { [key: string]: string[] } = {
        irrigation: ["irrigation"],
        nutrition: ["nutrition"],
        nutrition_2: ["nutrition_2"],
        illumination: ["illumination"],
        sht: ["climate"],
        climate: ["climate"]
    };

    const connectorTypes = dashboardMap[sensorType] || [];
    if (!connectorTypes.length) return;

    let dash: any | undefined;

    for (const candidate of connectorTypes) {
        const [foundDash] = await account.dashboards.list({
            amount: 1,
            fields: ["id", "tags"],
            filter: {
                tags: [{ key: "connector_id", value: candidate }]
            }
        });

        if (foundDash) {
            dash = foundDash;
            break;
        }
    }

    if (!dash) {
        console.warn("Dashboard nao encontrado para tipo " + sensorType);
        return;
    }

    const dashboardUrl = "https://admin.tago.io/dashboards/info/" + dash.id + "?org_dev=" + organizationId + "&group_dev=" + groupId + "&sensor=" + deviceId;

    await account.devices.paramSet(deviceId, {
        key: "dashboard_url",
        value: dashboardUrl,
        sent: false
    });

    console.log("Dashboard URL configurado para sensor " + serialNumber + " com tipo " + sensorType);
}

async function getDeviceByCandidate(account: Account, candidate?: string): Promise<any | null> {
    if (!candidate) return null;

    try {
        return await account.devices.info(candidate);
    } catch (_) {
        // O candidato pode ser ID logico/nome/tag em vez de ID do device.
    }

    const tagKeys = ["organization_id", "organization_device", "org_id", "company_id", "group_id", "user_org_id"];
    for (const key of tagKeys) {
        try {
            const devices = await account.devices.list({
                page: 1,
                amount: 1,
                fields: ["id", "name", "tags"],
                filter: { tags: [{ key, value: candidate }] }
            });

            if (devices.length) return devices[0];
        } catch (_) {
            // Continua tentando outros aliases.
        }
    }

    return null;
}

async function resolveRetentionDays(account: Account, centralDevice: any, organizationId?: string, groupId?: string): Promise<number> {
    const centralRetention = getRetentionDaysFromTags(centralDevice.tags);
    if (centralRetention) return centralRetention;

    const candidates = Array.from(new Set([
        getTagValue(centralDevice.tags, "organization_device"),
        organizationId,
        getTagValue(centralDevice.tags, "org_id"),
        getTagValue(centralDevice.tags, "company_id"),
        groupId
    ].filter(Boolean).map((item) => String(item))));

    for (const candidate of candidates) {
        const device = await getDeviceByCandidate(account, candidate);
        const retention = getRetentionDaysFromTags(device?.tags);
        if (retention) return retention;
    }

    return DEFAULT_RETENTION_DAYS;
}

function parseAutoValue(value: any): number | null {
    if (value === undefined || value === null || value === "") return null;
    const parsed = Number(String(value).replace(",", "."));
    return Number.isFinite(parsed) ? Math.floor(parsed) : null;
}

interface SensorData {
    MOD: number;
    EN: boolean;
    RG: boolean;
    OBJ: string;
    LIM: string;
    TEMP?: string;
    HUM?: string;
    CON?: string;
    SAL?: string;
    TDS?: string;
    EPS?: string;
    PW?: string;
    SOL?: string;
    COMM?: number;
    Auto?: number | string;
    ERRO?: Record<string, number>;
    [key: string]: any;
}

interface UplinkMessage {
    SN: string;
    FWV: string;
    configDevice?: string;
    devId?: string;
    data: {
        status?: any;
        sens?: {
            [sensorNumber: string]: SensorData;
        };
        Time?: any;
        fert?: any;
        Out?: any;
    };
}

/**
 * Função principal que verifica se deve cadastrar sensores automaticamente
 * e executa o cadastro na TagoIO
 * 
 * @param messageData - Dados da mensagem MQTT recebida
 * @param connectorId - ID do connector TagoIO (opcional)
 * @param networkId - ID do network no connector (opcional, mesmo valor do connectorId geralmente)
 */
export async function autoRegisterSensors(
    messageData: any,
    connectorId?: string,
    networkId?: string
): Promise<void> {
    try {
        // Parse da mensagem se vier como string
        const data: UplinkMessage = typeof messageData === 'string'
            ? JSON.parse(messageData)
            : messageData;

        // Verifica se a flag configDevice está ativa
        if (data.configDevice !== "true") {
            console.debug("configDevice não está ativo, pulando autocadastro");
            return;
        }

        console.log(`🔧 Iniciando autocadastro de sensores para central ${data.SN}`);
        console.log(`🔌 Connector ID: ${connectorId || 'NÃO FORNECIDO'}`);
        console.log(`🌐 Network ID: ${networkId || 'NÃO FORNECIDO'}`);

        // Valida se há dados de sensores
        if (!data.data?.sens) {
            console.warn("Nenhum sensor encontrado na mensagem");
            return;
        }

        // Inicializa a conta TagoIO
        const account = new Account({ token: ACCOUNT_TOKEN });

        // Busca a central existente pelo serial number
        console.log(`🔍 Buscando central ${data.SN}...`);
        const centralDevices = await account.devices.list({
            page: 1,
            amount: 1,
            fields: ["id", "name", "tags"],
            filter: {
                tags: [
                    { key: "serial_number", value: data.SN }
                ]
            }
        });

        if (centralDevices.length === 0) {
            throw new Error(`Central com serial number ${data.SN} não encontrada na TagoIO. Cadastre a central primeiro.`);
        }

        const centralDevice = centralDevices[0];
        console.log(`✅ Central encontrada: ${centralDevice.name} (ID: ${centralDevice.id})`);

        // Extrai group_id e organization_id das tags da central
        const groupId = getTagValue(centralDevice.tags, "group_id");
        const organizationId = getTagValue(centralDevice.tags, "organization_id");
        const retentionDays = await resolveRetentionDays(account, centralDevice, organizationId, groupId);

        if (!groupId) {
            console.warn(`⚠️ Tag 'group_id' não encontrada na central ${data.SN}`);
        }
        if (!organizationId) {
            console.warn(`⚠️ Tag 'organization_id' não encontrada na central ${data.SN}`);
        }

        console.log(`📋 group_id: ${groupId}, organization_id: ${organizationId}, retenção=${retentionDays} dias`);

        // Cadastra cada sensor individualmente
        const sensorNumbers = Object.keys(data.data.sens);
        let successCount = 0;
        let errorCount = 0;

        for (const sensorNumber of sensorNumbers) {
            const sensorConfig = data.data.sens[sensorNumber];
            const serialNumber = `${data.SN}_${sensorNumber}`;

            try {
                await registerSensorDevice(
                    account,
                    serialNumber,
                    data.SN,
                    sensorNumber,
                    sensorConfig,
                    groupId,
                    organizationId,
                    retentionDays,
                    connectorId,
                    networkId
                );
                successCount++;
                console.log(`✅ Sensor ${serialNumber} cadastrado com sucesso`);
            } catch (error) {
                errorCount++;
                console.error(`❌ Erro ao cadastrar sensor ${serialNumber}:`, error);
            }
        }

        console.log(`\n📊 Resumo do autocadastro:`);
        console.log(`   Central: ${data.SN}`);
        console.log(`   Total de sensores: ${sensorNumbers.length}`);
        console.log(`   Cadastrados: ${successCount}`);
        console.log(`   Erros: ${errorCount}`);

    } catch (error) {
        console.error("❌ Erro no processo de autocadastro:", error);
        throw error;
    }
}

/**
 * Cadastra um sensor na TagoIO usando API REST
 */
async function registerSensorDevice(
    account: Account,
    serialNumber: string,
    centralSN: string,
    sensorNumber: string,
    sensorConfig: SensorData,
    groupId?: string,
    organizationId?: string,
    retentionDays: number = DEFAULT_RETENTION_DAYS,
    connectorId?: string,
    networkId?: string
): Promise<void> {
    try {
        const autoValue = parseAutoValue(sensorConfig.Auto ?? sensorConfig.auto);
        const autoLabel = autoValue !== null ? (AUTO_TYPES[autoValue] || `Auto ${autoValue}`) : "Não informado";
        const devMode = autoValue === 5 ? "monitoring" : "automation";

        // Define o tipo de sensor baseado no MOD.
        // MOD 5 representa SHT; MOD 6 representa ClimaPrime.
        const sensorMod = Number(sensorConfig.MOD);
        const sensorType = SENSOR_TYPES_BY_MOD[sensorMod] || "irrigation";
        const sensorLabel = SENSOR_LABELS_BY_MOD[sensorMod] || SENSOR_LABELS[sensorType] || "Sensor";
        const applicationLabel = sensorMod === 5 ? "SHT - Climatização" : sensorMod === 6 ? "ClimaPrime - Climatização" : "UTC - " + sensorLabel;
        const sensorDeviceName = `${sensorLabel} ${sensorNumber} - Central ${centralSN}`;
        const retentionConfig = getDeviceRetentionConfig(retentionDays);
        const retentionLabel = formatRetentionConfig(retentionDays);

        // Verifica se o sensor já existe
        console.log(`🔍 Verificando se sensor ${serialNumber} já existe...`);
        try {
            const listResponse = await account.devices.list({ 
                page: 1, 
                amount: 1,
                fields: ["id", "name", "tags"],
                filter: {
                    tags: [{ key: "dev_eui", value: serialNumber }]
                }
            });
            console.log(`Resposta da verificação de existência do sensor ${serialNumber}:`, listResponse);
            if (listResponse && listResponse.length > 0) {
                const existingDevice = listResponse[0];
                const existingDeviceUpdate: any = {
                    chunk_period: retentionConfig.chunk_period,
                    chunk_retention: retentionConfig.chunk_retention,
                    tags: upsertTags(existingDevice.tags || [], [
                        { key: "plan_retention_days", value: String(retentionDays) },
                        { key: "central_sn", value: centralSN },
                        { key: "sensor_number", value: sensorNumber },
                        ...(groupId ? [{ key: "group_id", value: groupId }] : []),
                        ...(organizationId ? [{ key: "organization_id", value: organizationId }] : []),
                        ...(autoValue !== null ? [{ key: "auto", value: String(autoValue) }] : []),
                        { key: "auto_label", value: autoLabel },
                        { key: "sensor", value: sensorType },
                        { key: "sensor_label", value: sensorLabel },
                        { key: "application", value: sensorType },
                        { key: "application_label", value: applicationLabel },
                        { key: "sensor_mod", value: String(sensorConfig.MOD ?? "") },
                        { key: "device_type", value: "device" },
                        { key: "dev_mode", value: devMode }
                    ])
                };

                if (shouldUpdateAutoGeneratedSensorName(existingDevice.name, sensorNumber, centralSN, sensorDeviceName)) {
                    existingDeviceUpdate.name = sensorDeviceName;
                    console.log("Atualizando nome automatico do sensor " + serialNumber + " de " + existingDevice.name + " para " + sensorDeviceName);
                }

                await account.devices.edit(existingDevice.id, existingDeviceUpdate);
                try {
                    await configureDashboardUrl(account, existingDevice.id, serialNumber, sensorType, groupId, organizationId);
                } catch (dashError) {
                    console.warn("Erro ao atualizar dashboard_url do sensor existente:", dashError);
                }
                console.log(`📡 Sensor ${serialNumber} já cadastrado. Tipo ${sensorLabel} e retenção ${retentionLabel} atualizados.`);
                return;
            }
        } catch (listError) {
            console.log(`⚠️ Erro ao verificar existência do sensor, continuando com criação...`);
        }


        // Cria o dispositivo do sensor
        const deviceConfig: any = {
            name: sensorDeviceName,
            type: "immutable",
            serie_number: serialNumber,
            connector: "669188217d61980008c18be1",
            network: "6686e259ffa21c0008faa296",
            chunk_period: retentionConfig.chunk_period,
            chunk_retention: retentionConfig.chunk_retention,
            tags: [
                { key: "dev_eui", value: serialNumber },
                { key: "central_sn", value: centralSN },
                { key: "sensor_number", value: sensorNumber },
                ...(groupId ? [{ key: "group_id", value: groupId }] : []),
                ...(organizationId ? [{ key: "organization_id", value: organizationId }] : []),
                { key: "plan_retention_days", value: String(retentionDays) },
                ...(autoValue !== null ? [{ key: "auto", value: String(autoValue) }] : []),
                { key: "auto_label", value: autoLabel },
                { key: "sensor", value: sensorType },
                { key: "sensor_label", value: sensorLabel },
                { key: "application", value: sensorType },
                { key: "application_label", value: applicationLabel },
                { key: "sensor_mod", value: String(sensorConfig.MOD ?? "") },
                { key: "device_type", value: "device" },
                { key: "dev_mode", value: devMode },
            ],

        };
        console.log(`Configuração do dispositivo para sensor ${serialNumber}:`, deviceConfig);
        try {

            const createResponse = await account.devices.create(deviceConfig);
            const deviceId = createResponse.device_id;
            console.log(`✅ Sensor ${serialNumber} cadastrado com ID: ${deviceId}`);

            // Adiciona tag device_id ao sensor recém-criado
            try {
                await account.devices.edit(deviceId, {
                    tags: [
                        ...deviceConfig.tags,
                        { key: "device_id", value: deviceId }
                    ]
                });
                console.log(`🏷️ Tag device_id adicionada ao sensor ${serialNumber}`);
            } catch (tagError) {
                console.warn(`⚠️ Erro ao adicionar tag device_id:`, tagError);
            }

            // Cria token de autorização para o sensor
            try {
                const deviceAuthToken = await account.ServiceAuthorization.tokenCreate({
                    name: `${serialNumber}_token`,
                    permission: "full"
                });

                console.log(`🔑 Token de autorização criado para sensor ${serialNumber}`);
            } catch (tokenError) {
                console.warn(`⚠️ Erro ao criar token de autorização:`, tokenError);
            }

            // Configura parâmetros adicionais do device
            try {
                await account.devices.paramSet(deviceId, { key: "dev_eui", value: serialNumber, sent: false });
                await account.devices.paramSet(deviceId, { key: "dev_lastcheckin", value: "-", sent: false });
                await account.devices.paramSet(deviceId, { key: "dev_battery", value: "-", sent: false });
            } catch (paramError) {
                console.warn(`⚠️ Erro ao configurar parâmetros adicionais:`, paramError);
            }

            // Configura o dashboard_url baseado no tipo de sensor
            try {
                const dashboardMap: { [key: string]: string[] } = {
                    'irrigation': ['irrigation'],
                    'nutrition': ['nutrition'],
                    'nutrition_2': ['nutrition_2'],
                    'illumination': ['illumination'],
                    'sht': ['climate'],
                    'climate': ['climate']
                };

                const connectorTypes = dashboardMap[sensorType] || [];
                if (connectorTypes.length) {
                    let dash: any | undefined;
                    let connectorType = "";

                    for (const candidate of connectorTypes) {
                        // Busca dashboard pelo connector_id (tipo de sensor)
                        const [foundDash] = await account.dashboards.list({
                            amount: 1,
                            fields: ["id", "tags"],
                            filter: {
                                tags: [{ key: "connector_id", value: candidate }]
                            }
                        });

                        if (foundDash) {
                            dash = foundDash;
                            connectorType = candidate;
                            break;
                        }
                    }

                    if (dash) {
                        const dashboardUrl = `https://admin.tago.io/dashboards/info/${dash.id}?org_dev=${organizationId}&group_dev=${groupId}&sensor=${deviceId}`;
                        
                        await account.devices.paramSet(deviceId, {
                            key: "dashboard_url",
                            value: dashboardUrl,
                            sent: false
                        });
                        
                        console.log(`📊 Dashboard URL configurado para sensor ${serialNumber}`);
                    } else {
                        console.warn(`⚠️ Dashboard não encontrado para tipo ${sensorType}`);
                    }
                }
            } catch (dashError) {
                console.warn(`⚠️ Erro ao configurar dashboard_url:`, dashError);
            }

        } catch (createError) {
            console.error(`❌ Erro ao criar sensor ${serialNumber}:`, createError);
            throw createError;
        }


    } catch (error) {
        console.error(`Erro ao cadastrar sensor ${serialNumber}:`, error);
        throw error;
    }
}

/**
 * Função auxiliar para validar se uma mensagem deve acionar o autocadastro
 */
export function shouldAutoRegister(data: any): boolean {
    try {
        const parsed = typeof data === 'string' ? JSON.parse(data) : data;
        return parsed.configDevice === "true" && parsed.data?.sens !== undefined;
    } catch (error) {
        return false;
    }
}
